name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navegar até a pasta do projeto
            cd projeto_resistencia
            
            # Garantir que estamos na branch correta e baixar atualizações
            git checkout main
            git pull origin main
            
            # Rodar o script de deploy existente
            # Torná-lo executável por precaução
            chmod +x deploy.sh
            ./deploy.sh
